package Models.java;
import genDevs.modeling.*;
import genDevs.simulation.*;
import java.util.*;
import GenCol.*;
import simView.*;
import java.awt.*;

public class bidTest extends ViewableDigraph{
    
    
    public bidTest(){
        super("bitTest");
        addOutport("outJob");
        
        ViewableAtomic bidProcInstance = new bidProc();
        add(bidProcInstance);
        
        ViewableAtomic bidCoordInstance = new bidCoord();
        add(bidCoordInstance);
        
        
        //addCoupling(bidProcInstance,"outJob",bidProcInstance,"inJob");
        
        addCoupling(bidCoordInstance,"outJob",bidProcInstance,"inJob");
        
        //// addCoupling(bidProcInstance,"outJob",bidCoordInstance,"inJob");
        
        //addCoupling(bidCoordInstance,"outJob",bidCoordInstance,"inJob");
        
        
        addCoupling(bidCoordInstance,"outfree?",bidProcInstance,"infree?");
        
        addCoupling(bidProcInstance,"outBid",bidCoordInstance,"inBid");
        
        
        
        addCoupling(bidProcInstance,"outJobDone",bidCoordInstance,"inJobDone");
        addCoupling(bidCoordInstance,"outJobDone",this,"outJob");
        
    }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView() {
        ComputeLayout = false;
        preferredSize = new Dimension(673, 478);
        if (withName("bidCoord")!=null)
            ((ViewableComponent)withName("bidCoord")).setPreferredLocation(new Point(233, 129));
        if (withName("bidProc")!=null)
            ((ViewableComponent)withName("bidProc")).setPreferredLocation(new Point(257, 262));
    }
}
