package Models.java;

import genDevs.modeling.*;
import genDevs.simulation.*;
import java.util.*;
import GenCol.*;
import simView.*;
import java.awt.*;

public class DrumEar extends ViewableDigraph{

public DrumEar(){
this("DrumEar");}

public DrumEar(String nm){
super(nm);

	ViewableAtomic DrumInstance = new Drum();
	add(DrumInstance);

	ViewableAtomic EarInstance = new Ear();
	add(EarInstance);


	addCoupling(DrumInstance,"outBeat",EarInstance,"inBeat");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
ComputeLayout = false;
        preferredSize = new Dimension(673, 478);
        if (withName("Drum")!=null)
             ((ViewableComponent)withName("Drum")).setPreferredLocation(new Point(230, 195));
        if (withName("Ear")!=null)
             ((ViewableComponent)withName("Ear")).setPreferredLocation(new Point(374, 194));
    }
}
