package Models.java;

import genDevs.modeling.*;
import genDevs.simulation.*;
import java.util.*;
import GenCol.*;
import simView.*;
import java.awt.*;

public class InteropTestBed extends ViewableDigraph{

public InteropTestBed(){
this("InteropTestBed");}

public InteropTestBed(String nm){
super(nm);

	ViewableAtomic SUTInstance = new SUT();
	add(SUTInstance);

	ViewableAtomic ATCGenObserverInstance = new ATCGenObserver();
	add(ATCGenObserverInstance);
        
	ViewableAtomic ATCGenrInstance = new ATCGenGenr();
	add(ATCGenrInstance);
        
        
	ViewableAtomic SensorSimInstance = new SensorSim();
	add(SensorSimInstance);


	addCoupling(SUTInstance,"outRRCommand",ATCGenObserverInstance,"inRRCommand");

	addCoupling(SensorSimInstance,"outRadarTrack",SUTInstance,"inRadarTrack");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
ComputeLayout = false;
        preferredSize = new Dimension(673, 478);
        if (withName("ATCGenr")!=null)
             ((ViewableComponent)withName("ATCGenr")).setPreferredLocation(new Point(127, 88));
        if (withName("SensorSim")!=null)
             ((ViewableComponent)withName("SensorSim")).setPreferredLocation(new Point(69, 234));
        if (withName("ATCGenObserver")!=null)
             ((ViewableComponent)withName("ATCGenObserver")).setPreferredLocation(new Point(377, 98));
        if (withName("SUT")!=null)
             ((ViewableComponent)withName("SUT")).setPreferredLocation(new Point(332, 279));
    }
}
