package Models.java;

import genDevs.modeling.*;
import genDevs.simulation.*;
import java.util.*;
import GenCol.*;
import simView.*;
import java.awt.*;

public class pipArch extends ViewableDigraph{

public pipArch(){
this("pipArch");}

public pipArch(String nm){
super(nm);

	ViewableAtomic procWport2Instance = new procWport2();
	add(procWport2Instance);

	ViewableAtomic pipeCoordInstance = new pipeCoord();
	add(pipeCoordInstance);

	ViewableAtomic procWport1Instance = new procWport1();
	add(procWport1Instance);


	addCoupling(procWport2Instance,"outJob2",pipeCoordInstance,"inJob2");

	addCoupling(procWport1Instance,"outJob1",pipeCoordInstance,"inJob1");

	addCoupling(pipeCoordInstance,"outJ2",procWport2Instance,"inJ2");

	addCoupling(pipeCoordInstance,"outJ1",procWport1Instance,"inJ1");

}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
ComputeLayout = false;
        preferredSize = new Dimension(673, 478);
        if (withName("pipeCoord")!=null)
             ((ViewableComponent)withName("pipeCoord")).setPreferredLocation(new Point(254, 114));
        if (withName("procWport2")!=null)
             ((ViewableComponent)withName("procWport2")).setPreferredLocation(new Point(354, 313));
        if (withName("procWport1")!=null)
             ((ViewableComponent)withName("procWport1")).setPreferredLocation(new Point(121, 288));
    }
}
