/*
 * PanelXmlPane.java
 *
 * Created on July 12, 2007, 10:31 PM
 */

package genDevs.jaxb.gui;

/**
 *
 * @author  Saurabh
 */
public class PanelTextArea extends javax.swing.JPanel {
    
    /** Creates new form PanelXmlPane */
    public PanelTextArea() {
        initComponents();
    }
    
    public void setText(String text){
        jtaXmlArea.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaXmlArea = new javax.swing.JTextArea();

        jtaXmlArea.setColumns(20);
        jtaXmlArea.setFont(new java.awt.Font("Courier New", 0, 11));
        jtaXmlArea.setRows(5);
        jScrollPane1.setViewportView(jtaXmlArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaXmlArea;
    // End of variables declaration//GEN-END:variables
    
}
