//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.17 at 10:47:59 PM MST 
//


package com.acims.fddevs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for atomicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="atomicType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}inports"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}outports"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}states"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}deltint"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}deltext"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}TimeAdvance"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}LamdaSet"/>
 *       &lt;/sequence>
 *       &lt;attribute name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "atomic", propOrder = {
    "inportsAndOutportsAndStates"
})
@XmlRootElement
public class AtomicType {

    @XmlElements({
        @XmlElement(name = "deltext", type = DeltextType.class),
        @XmlElement(name = "deltint", type = DeltintType.class),
        @XmlElement(name = "TimeAdvance", type = TimeAdvanceType.class),
        @XmlElement(name = "inports", type = InportType.class),
        @XmlElement(name = "LamdaSet", type = LamdaAllType.class),
        @XmlElement(name = "outports", type = OutportType.class),
        @XmlElement(name = "states", type = StatesType.class)
    })
    protected List<Object> inportsAndOutportsAndStates;
    @XmlAttribute
    protected String modelName;
    @XmlAttribute
    protected String host;

    /**
     * Gets the value of the inportsAndOutportsAndStates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inportsAndOutportsAndStates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInportsAndOutportsAndStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeltextType }
     * {@link DeltintType }
     * {@link TimeAdvanceType }
     * {@link InportType }
     * {@link LamdaAllType }
     * {@link OutportType }
     * {@link StatesType }
     * 
     * 
     */
    public List<Object> getInportsAndOutportsAndStates() {
        if (inportsAndOutportsAndStates == null) {
            inportsAndOutportsAndStates = new ArrayList<Object>();
        }
        return this.inportsAndOutportsAndStates;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

}
