//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.17 at 10:47:59 PM MST 
//


package com.acims.fddevs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for extTransitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="extTransitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}IncomingMessage"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}transition"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}scheduleIndicator"/>
 *       &lt;/sequence>
 *       &lt;attribute name="extTransitionID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extTransitionType", propOrder = {
    "incomingMessage",
    "transition",
    "scheduleIndicator"
})
public class ExtTransitionType {

    @XmlElement(name = "IncomingMessage", required = true)
    protected String incomingMessage;
    @XmlElement(required = true)
    protected TransitionType transition;
    protected boolean scheduleIndicator;
    @XmlAttribute(required = true)
    protected int extTransitionID;

    /**
     * Gets the value of the incomingMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomingMessage() {
        return incomingMessage;
    }

    /**
     * Sets the value of the incomingMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomingMessage(String value) {
        this.incomingMessage = value;
    }

    /**
     * Gets the value of the transition property.
     * 
     * @return
     *     possible object is
     *     {@link TransitionType }
     *     
     */
    public TransitionType getTransition() {
        return transition;
    }

    /**
     * Sets the value of the transition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransitionType }
     *     
     */
    public void setTransition(TransitionType value) {
        this.transition = value;
    }

    /**
     * Gets the value of the scheduleIndicator property.
     * 
     */
    public boolean isScheduleIndicator() {
        return scheduleIndicator;
    }

    /**
     * Sets the value of the scheduleIndicator property.
     * 
     */
    public void setScheduleIndicator(boolean value) {
        this.scheduleIndicator = value;
    }

    /**
     * Gets the value of the extTransitionID property.
     * 
     */
    public int getExtTransitionID() {
        return extTransitionID;
    }

    /**
     * Sets the value of the extTransitionID property.
     * 
     */
    public void setExtTransitionID(int value) {
        this.extTransitionID = value;
    }

}
