//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.17 at 10:47:59 PM MST 
//


package com.acims.fddevs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}StartState"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/NewXMLSchema}NextState"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transitionType", propOrder = {
    "startState",
    "nextState"
})
public class TransitionType {

    @XmlElement(name = "StartState", required = true)
    protected String startState;
    @XmlElement(name = "NextState", required = true)
    protected String nextState;

    /**
     * Gets the value of the startState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartState() {
        return startState;
    }

    /**
     * Sets the value of the startState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartState(String value) {
        this.startState = value;
    }

    /**
     * Gets the value of the nextState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextState() {
        return nextState;
    }

    /**
     * Sets the value of the nextState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextState(String value) {
        this.nextState = value;
    }

}
