//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 11:06:30 PM MST 
//


package com.acims.coupled;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CouplingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CouplingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.saurabh-mittal.com/CoupledDevs}SrcModel"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/CoupledDevs}outport"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/CoupledDevs}DestModel"/>
 *         &lt;element ref="{http://www.saurabh-mittal.com/CoupledDevs}inport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CouplingType", propOrder = {
    "srcModel",
    "outport",
    "destModel",
    "inport"
})
public class CouplingType {

    @XmlElement(name = "SrcModel", required = true)
    protected String srcModel;
    @XmlElement(required = true)
    protected String outport;
    @XmlElement(name = "DestModel", required = true)
    protected String destModel;
    @XmlElement(required = true)
    protected String inport;

    /**
     * Gets the value of the srcModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcModel() {
        return srcModel;
    }

    /**
     * Sets the value of the srcModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcModel(String value) {
        this.srcModel = value;
    }

    /**
     * Gets the value of the outport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutport() {
        return outport;
    }

    /**
     * Sets the value of the outport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutport(String value) {
        this.outport = value;
    }

    /**
     * Gets the value of the destModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestModel() {
        return destModel;
    }

    /**
     * Sets the value of the destModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestModel(String value) {
        this.destModel = value;
    }

    /**
     * Gets the value of the inport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInport() {
        return inport;
    }

    /**
     * Sets the value of the inport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInport(String value) {
        this.inport = value;
    }

}
