//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 11:06:30 PM MST 
//


package com.acims.coupled;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.acims.coupled package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Outport_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "outport");
    private final static QName _Inport_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "inport");
    private final static QName _Coupling_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "Coupling");
    private final static QName _Digraph_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "Digraph");
    private final static QName _SrcModel_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "SrcModel");
    private final static QName _Model_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "Model");
    private final static QName _Models_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "Models");
    private final static QName _DestModel_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "DestModel");
    private final static QName _Couplings_QNAME = new QName("http://www.saurabh-mittal.com/CoupledDevs", "Couplings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.acims.coupled
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CouplingsType }
     * 
     */
    public CouplingsType createCouplingsType() {
        return new CouplingsType();
    }

    /**
     * Create an instance of {@link CouplingType }
     * 
     */
    public CouplingType createCouplingType() {
        return new CouplingType();
    }

    /**
     * Create an instance of {@link DigraphType }
     * 
     */
    public DigraphType createDigraphType() {
        return new DigraphType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link ModelsType }
     * 
     */
    public ModelsType createModelsType() {
        return new ModelsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "outport")
    public JAXBElement<String> createOutport(String value) {
        return new JAXBElement<String>(_Outport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "inport")
    public JAXBElement<String> createInport(String value) {
        return new JAXBElement<String>(_Inport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CouplingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "Coupling")
    public JAXBElement<CouplingType> createCoupling(CouplingType value) {
        return new JAXBElement<CouplingType>(_Coupling_QNAME, CouplingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigraphType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "Digraph")
    public JAXBElement<DigraphType> createDigraph(DigraphType value) {
        return new JAXBElement<DigraphType>(_Digraph_QNAME, DigraphType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "SrcModel")
    public JAXBElement<String> createSrcModel(String value) {
        return new JAXBElement<String>(_SrcModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "Model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "Models")
    public JAXBElement<ModelsType> createModels(ModelsType value) {
        return new JAXBElement<ModelsType>(_Models_QNAME, ModelsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "DestModel")
    public JAXBElement<String> createDestModel(String value) {
        return new JAXBElement<String>(_DestModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CouplingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.saurabh-mittal.com/CoupledDevs", name = "Couplings")
    public JAXBElement<CouplingsType> createCouplings(CouplingsType value) {
        return new JAXBElement<CouplingsType>(_Couplings_QNAME, CouplingsType.class, null, value);
    }

}
