//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 11:06:30 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.saurabh-mittal.com/CoupledDevs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.acims.coupled;
